"""init

Revision ID: d0389b2101d4
Revises: 768114a9d30f
Create Date: 2024-04-08 16:08:41.526560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0389b2101d4'
down_revision: Union[str, None] = '768114a9d30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('well', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_currencies'))
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.String(length=255), nullable=False),
    sa.Column('gold', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_teams')),
    sa.UniqueConstraint('aliases', name=op.f('uq_teams_aliases'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('tris', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('gold', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('farm_gold', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('currencies')
    # ### end Alembic commands ###
